language: clojure
sudo: false
lein: lein2
install: lein2 sub -s "lein-finagle-clojure:finagle-clojure-template:core:thrift" install
script: lein2 sub with-profile dev:1.5,test:1.4,test midje
jdk:
    - openjdk7
